<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class AsetPerangkatLunakSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0018',
                'nama_aset'          => 'Windows Server 2016 Standard [SIMRS]',
                'keterangan'         => 'OS yang digunakan oleh simrs database dan dhcp server',
                'sub_klasifikasi_id' => 'a1b93053-cfa4-46af-84a4-d4ee89be1390',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0019',
                'nama_aset'          => 'Ubuntu 2402 [SIMRS]',
                'keterangan'         => 'OS yang digunakan oleh SIMRS aplikasi dan database',
                'sub_klasifikasi_id' => 'a1b93053-cfa4-46af-84a4-d4ee89be1390',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0021',
                'nama_aset'          => 'OS Mikrotik Router OS [SIMRS]',
                'keterangan'         => 'Sistem operasi yang digunakan oleh router mikrotik',
                'sub_klasifikasi_id' => 'a1b93053-cfa4-46af-84a4-d4ee89be1390',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0041',
                'nama_aset'          => 'Ubuntu 24.04 LTS [Datin]',
                'keterangan'         => '1 Unit /OS digunakan untuk SIMRS',
                'sub_klasifikasi_id' => 'a1b93053-cfa4-46af-84a4-d4ee89be1390',
                'opd_id'             => 26,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0062',
                'nama_aset'          => 'Windows Server {**Aset dengan model berbeda agar diinput baru}',
                'keterangan'         => 'Windows server 2016 dan 2019 standard',
                'sub_klasifikasi_id' => 'a1b93053-cfa4-46af-84a4-d4ee89be1390',
                'opd_id'             => 29,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0063',
                'nama_aset'          => 'Ubuntu Server',
                'keterangan'         => 'Sistem Operasi Server E-Plan',
                'sub_klasifikasi_id' => 'a1b93053-cfa4-46af-84a4-d4ee89be1390',
                'opd_id'             => 3,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0135',
                'nama_aset'          => 'OS Server VMWare ESXi',
                'keterangan'         => '10 unit ESXi 6.0, 1 unit ESXi 7.0',
                'sub_klasifikasi_id' => 'a1b93053-cfa4-46af-84a4-d4ee89be1390',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0020',
                'nama_aset'          => 'Eset Endpoint Antivirus [SIM RS]',
                'keterangan'         => '72 aktivasi device (10 Server + 62 Client) untuk melindungi komputer dari virus, malware, dan program jahat lainnya',
                'sub_klasifikasi_id' => 'a1b93053-cfd2-46f8-8219-61bbb06f37fc',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0040',
                'nama_aset'          => 'Antivirus Kaspersky [Datin]',
                'keterangan'         => '2 unit / Antivirus untuk melindungi Endpoint dari malware, ransomware, serta ancaman siber',
                'sub_klasifikasi_id' => 'a1b93053-cfd2-46f8-8219-61bbb06f37fc',
                'opd_id'             => 26,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0109',
                'nama_aset'          => 'Microsoft SQL Server [SIMRS]',
                'keterangan'         => 'Database engine SIMRS',
                'sub_klasifikasi_id' => 'a1b93053-cfd2-46f8-8219-61bbb06f37fc',
                'opd_id'             => 29,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0114',
                'nama_aset'          => 'Antivirus Kaspersky [TI]',
                'keterangan'         => '7 unit  / Antivirus Kaspersky keamanan endpoint canggih yang dirancang untuk mendeteksi, menganalisis, dan merespons ancaman siber secara real-time.',
                'sub_klasifikasi_id' => 'a1b93053-cfd2-46f8-8219-61bbb06f37fc',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0001',
                'nama_aset'          => 'Website BPKAD Provinsi Bali',
                'keterangan'         => 'Sebagai sarana informasi Publik, transparansi dan akuntabilitas. https://bpkad.baliprov.go.id/',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0002',
                'nama_aset'          => 'SIWA',
                'keterangan'         => 'Aplikasi Sewa Aset Daerah Provinsi Bali. https://aset.baliprov.go.id/',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0004',
                'nama_aset'          => 'SIMRS [Datin]',
                'keterangan'         => 'Aplikasi digunakan untuk manajemen rumah sakit. Akses internal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 26,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0005',
                'nama_aset'          => 'Website Sekretariat DPRD Provinsi Bali',
                'keterangan'         => 'Berisikan informasi kegiatan-kegiatan yang ada di DPRD Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 33,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0006',
                'nama_aset'          => 'Website JDIH DPRD Provinsi Bali',
                'keterangan'         => 'Berisikan informasi produk-produk hukum yang dihasilkan di DPRD Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 33,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0007',
                'nama_aset'          => 'Sensus Semesta Berencana Sumber Daya Bali Berbasis Desa Adat',
                'keterangan'         => 'Aplikasi Pendataan Desa Adat di Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 23,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0008',
                'nama_aset'          => 'Jurnal Bali Membangun Bali (JBMB)',
                'keterangan'         => 'Aplikasi yang mengelola Jurnal di Pemerintah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 23,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0009',
                'nama_aset'          => 'Bali Sentra KI',
                'keterangan'         => 'Fasilitasi KI Pemprov Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 23,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0010',
                'nama_aset'          => 'Website RSBM [Humas]',
                'keterangan'         => 'Portal website Rumah Sakit Umum Daerah Bali Mandara',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0012',
                'nama_aset'          => 'SIMRS Bali Mandara [SIMRS]',
                'keterangan'         => 'Sistem Informasi Manajemen Rumah Sakit',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0013',
                'nama_aset'          => 'Aplikasi Mutu [SIMRS]',
                'keterangan'         => 'Aplikasi Pengendalian Mutu di RSBM',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0014',
                'nama_aset'          => 'RIS [SIMRS]',
                'keterangan'         => 'Radiology Information System / Sistem Informasi Radiologi di RSBM',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0016',
                'nama_aset'          => 'Aplikasi PACS [SIMRS]',
                'keterangan'         => 'Aplikasi yang digunakan dalam menyimpan data hasil image radiologi',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0017',
                'nama_aset'          => 'E-Perpus [SIMRS]',
                'keterangan'         => 'Aplikasi perpustakaan digital RSBM',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0022',
                'nama_aset'          => 'Aduan CSIRT [Persandian]',
                'keterangan'         => 'Sistem Tiket Aduan Kerentanan dan Insiden Siber Pemprov Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0023',
                'nama_aset'          => 'Elektonik Tindak Lanjut (E-TL)',
                'keterangan'         => 'Aplikasi Pemantauan Pemenuhan Tindak Lanjut Hasil Pemeriksaan Inspektorat Daerah Provinsi Bali di Lingkungan Pemerintah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 4,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0024',
                'nama_aset'          => 'Pemantauan Tindak Lanjut Pengaduan Masyarakat (PETI EMAS)',
                'keterangan'         => 'Sistem yang digunakan untuk melaksanakan pemantauan tindak lanjut pengaduan masyarakat di Pemerintah Provinsi Bali sebagai upaya meningkatkan pelayanan dalam menindaklanjuti pengaduan masyarakat yang diterima oleh Inspektorat Daerah Provinsi Bali di Pemerintah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 4,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0025',
                'nama_aset'          => 'Strategi Penguaran Penerapan Manajemen Risiko Berkualitas Melalui Aplikasi Terintegrasi (SUPERMANKUAT)',
                'keterangan'         => 'Aplikasi strategi penguatan dalam penerapan manajemen risiko dengan menerapkan kerangka manajemen risiko untuk mengidentifikasi kondisi/peristiwa potensial yang mungkin mempengaruhi pencapaian tujuan organisasi dan mengelola risiko yang mungkin terjadi, untuk memberikan keyakinan yang memadai pencapaian tujuan organisasi dapat terwujud dengan dengan melibatkan semua jenjang dalam organisasi (three lines of defence) untuk meningkatkan kualitas tata kelola.',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 4,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0026',
                'nama_aset'          => 'Whistleblowing System (WBS)',
                'keterangan'         => 'Aplikasi yang digunakan untuk melaporkan pelanggaran yang dilakukan oleh pegawai internal di lingkungan Pemerintah Provinsi Bali oleh pegawai atau masyarakat umum.',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 4,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0027',
                'nama_aset'          => 'Web Biro Pemerintahan dan Kesejahteraan Rakyat',
                'keterangan'         => 'Website resmi Biro Pemerintahan dan Kesejahteraan Rakyat Setda Provinsi Bali yang berfungsi sebagai media informasi publik, dan publikasi kegiatan',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 19,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0028',
                'nama_aset'          => 'Website Biro Umum Setda Provinsi Bali',
                'keterangan'         => 'Website yang menampilkan informasi dan layanan pada Biro Umum',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 10,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0032',
                'nama_aset'          => 'SIDOKAR [Datin]',
                'keterangan'         => 'Aplikasi digunakan untuk Manajemen Dokumen Akreditasi Rumah Sakit. Akses internal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 26,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0033',
                'nama_aset'          => 'Layanan Sisnaker Provinsi Bali yang terdiri dari Layanan Pendataan PMI Krama Bali, Sikomang Luri, Layanan Relasi',
                'keterangan'         => 'Operasional dan Manajemen Data/Konten Layanan Sisnaker Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 7,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0034',
                'nama_aset'          => 'Website Badan Penghubung Provinsi Bali',
                'keterangan'         => 'Website yang menampilkan informasi terkait Badan Penghubung Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 32,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0035',
                'nama_aset'          => 'Web-Site Informasi Dinas Pemajuan Masyarakat Adat Provinsi Bali',
                'keterangan'         => 'Web-Site Informasi Dinas Pemajuan Masyarakat Adat Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 13,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0036',
                'nama_aset'          => 'Website Dinas Ketenagakerjaan dan Energi Sumber Daya Mineral',
                'keterangan'         => 'Website Resmi Instansi',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 7,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0037',
                'nama_aset'          => 'BLUD [Datin]',
                'keterangan'         => 'Aplikasi di gunakan untuk Sistem Badan Layanan Umum Daerah. Akses Lokal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 26,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0038',
                'nama_aset'          => 'Website RSJ MSM [Datin]',
                'keterangan'         => 'Website resmi Rumah Sakit Jiwa Manah Shanti Mahottama',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 26,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0039',
                'nama_aset'          => 'Pendaftaran Online [Datin]',
                'keterangan'         => 'Aplikasi pendaftaran online RSJ',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 26,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0042',
                'nama_aset'          => 'Website dinas PUPRKIM',
                'keterangan'         => 'Website dinas PUPRKIM',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 9,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0044',
                'nama_aset'          => 'E-BMD',
                'keterangan'         => 'Aplikasi E-BMD merupakan aplikasi untuk membantu pelaksanaan penatausahaan Barang Milik Daerah Pemerintah Provinsi Bali sesuai ketentuan Permendagri 47 Tahun 2021. (https://baliprov.e-bmd.co.id/)',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0045',
                'nama_aset'          => 'SIPKD',
                'keterangan'         => 'SIPKD (Sistem Informasi Pengelolaan Keuangan Daerah), merupakan aplikasi terpadu untuk mengelola keuangan secara efisien, efektif, transparan, akuntabel, dan auditable.',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0047',
                'nama_aset'          => 'Website Badan Pendapatan Daerah Provinsi Bali',
                'keterangan'         => 'Website yang berisi tentang informasi dan berita terkait Bapenda Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 25,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0048',
                'nama_aset'          => 'Aplikasi PRESTISE',
                'keterangan'         => 'Aplikasi yang digunakan dalam pengurusan izin yang menjadi kewenangan Pemerintah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 8,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0050',
                'nama_aset'          => 'Portal TJSL Perusahaan Provinsi Bali',
                'keterangan'         => 'Aplikasi berbasis web mendukung penyelenggaraan program TJSL (Tanggung Jawab Sosial Lingkungan) Perusahaan Pemerintah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 3,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0051',
                'nama_aset'          => 'Website Pusat Informasi Investasi Kerthi Bali Sedhana',
                'keterangan'         => 'Website Pusat Informasi Investasi Kerthi Bali Sedhana',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 3,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0052',
                'nama_aset'          => 'Aplikasi E-Plan',
                'keterangan'         => 'Aplikasi berbasis web membantu proses perencanaan Hibahdan Pokir',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 3,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0053',
                'nama_aset'          => 'Website Biro PBJEK',
                'keterangan'         => 'Website resmi Biro Pengadaan Barang/Jasa dan Perekonomian Setda Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 17,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0054',
                'nama_aset'          => 'Aplikasi SIGAPURA',
                'keterangan'         => 'Operasional dan Manajemen Data/Konten Aplikasi SIGAPURA (https://sigapura.baliprov.go.id/)',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 17,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0055',
                'nama_aset'          => 'Website Dinas Pemberdayaan Masyarakat, Desa, Kependudukan, dan Pencatatan Sipil',
                'keterangan'         => 'Website yang menampilkan informasi terkait Dinas Website Dinas Pemberdayaan Masyarakat, Desa, Kependudukan, dan Pencatatan Sipil',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 16,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0056',
                'nama_aset'          => 'Web Dinas Perindustrian dan Perdagangan Provinsi Bali',
                'keterangan'         => 'Operasional dan manajemen data/konten Website',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 2,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0057',
                'nama_aset'          => 'Website Dinas Perhubungan Provinsi Bali [Sekretariat]',
                'keterangan'         => 'Website resmi yang berfungsi sebagai media informasi publik, dan publikasi kegiatan di Dinas Perhubungan Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 18,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0058',
                'nama_aset'          => 'SIMPADU BALI',
                'keterangan'         => 'Sistem Informasi Manajemen Perhubungan Terpadu Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 18,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0059',
                'nama_aset'          => 'Website Dinas Koperasi, Usaha Kecil dan Menengah Provinsi Bali',
                'keterangan'         => 'Website resmi yang berfungsi sebagai media informasi publik, dan publikasi kegiatan di Dinas Koperasi UKM Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 24,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0061',
                'nama_aset'          => 'Sistem Informasi Kesejahteraan Sosial Next Generation [PPFM]',
                'keterangan'         => 'istem data terpadu milik Kementerian Sosial Republik Indonesia yang berfungsi mengelola Data Terpadu Kesejahteraan Sosial (DTKS)',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 30,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0064',
                'nama_aset'          => 'SIK-KBS',
                'keterangan'         => 'Sistem Informasi Kesehatan Krama Bali Sejahtera',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 5,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0065',
                'nama_aset'          => 'Online Data Koperasi',
                'keterangan'         => 'Online Data Koperasi adalah suatu sistem yang dibuat oleh Pemerintah Provinsi Bali untuk mendukung pendataan Koperasi di Provinsi Bali.',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 24,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0067',
                'nama_aset'          => 'Office UMKM/IKM (UMKM)',
                'keterangan'         => 'Update Konten/Data UMKM di Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 24,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0068',
                'nama_aset'          => 'Made in Bali',
                'keterangan'         => 'Media katalog digital UMKM di Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 24,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0070',
                'nama_aset'          => 'Pustakabali',
                'keterangan'         => 'Layanan Otomasi Perpustakaan',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 12,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0071',
                'nama_aset'          => 'Website Biro Organisasi',
                'keterangan'         => 'Website Biro Organisasi Setda Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 12,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0072',
                'nama_aset'          => 'SIPELIK, Sistem Informasi Peta Konflik',
                'keterangan'         => 'Sistem Informasi untuk pendataan konflik sosial di Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 22,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0073',
                'nama_aset'          => 'Website Badan Kesatuan Bangsa dan Politik Provinsi Bali',
                'keterangan'         => 'Website menampilkan infomasi',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 22,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0074',
                'nama_aset'          => 'Website OPD [Sekretariat]',
                'keterangan'         => 'Website Resmi Dinas Pertanian dan Ketahanan Pangan Provinsi Bali (distanpangan.baliprov.go.id)',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 6,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0077',
                'nama_aset'          => 'Website Resmi Biro Hukum Setda Provinsi Bali',
                'keterangan'         => 'website untuk publikasi informasi publik serta kegiatan-kegiatan di Biro Hukum',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 15,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0078',
                'nama_aset'          => 'Website JDIH Provinsi Bali',
                'keterangan'         => 'sebuah sistem yang menyediakan akses mudah, cepat, dan akurat terhadap dokumen serta peraturan perundang-undangan secara terpadu dan teratur atau untuk publikasi produk hukum yang dipublikasikan pemerintah provinsi bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 15,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0079',
                'nama_aset'          => 'Website Dinas Kesehatan Provinsi Bali',
                'keterangan'         => 'Operasional dan Manajemen Data/konten website resmi dinas kesehatan',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 5,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0080',
                'nama_aset'          => 'Koneksi',
                'keterangan'         => 'Aplikasi Kepegawaian Online Efektif dan Efisien',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 28,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0081',
                'nama_aset'          => 'SI-MADE',
                'keterangan'         => 'Sistem Informasi Manajemen Aset Daerah',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 28,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0082',
                'nama_aset'          => 'SIAP SWASTISABA',
                'keterangan'         => 'Sistem Informasi Aplikasi (SIAP) SWASTISABA',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 5,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0083',
                'nama_aset'          => 'Office UMKM/IKM (IKM)',
                'keterangan'         => 'Aplikasi Pendataan Data IKM sebagai database Aplikasi Made In Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 2,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0084',
                'nama_aset'          => 'Website Dinas Pariwisata',
                'keterangan'         => 'Website Dinas Pariwisata',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 20,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0085',
                'nama_aset'          => 'SIMPELKAN',
                'keterangan'         => 'Sistem Pelayanan Perikanan',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 31,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0086',
                'nama_aset'          => 'Website OPD',
                'keterangan'         => 'Website Resmi Dinas Kelautan dan Perikanan Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 31,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0087',
                'nama_aset'          => 'Website Bappeda Bali',
                'keterangan'         => 'Website Bappeda Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 3,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0088',
                'nama_aset'          => 'Website Dinas Kebudayaan Provinsi Bali',
                'keterangan'         => 'Website Resmi Instansi',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 21,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0089',
                'nama_aset'          => 'Love Bali',
                'keterangan'         => 'Aplikasi Love Bali untuk Pungutan Wisatawan Asing',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 20,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0090',
                'nama_aset'          => 'Website Dinas Sosial, Pemberdayaan Perempuan dan Perlindungan Anak Provinsi Bali [Sekretariat]',
                'keterangan'         => 'Website yang menampilkan informasi terkait Dinas Sosial, Pemberdayaan Perempuan dan Perlindungan Anak Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 30,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0091',
                'nama_aset'          => 'Portal Biro PBJ (SIAP, SIPUT, Penomoran)',
                'keterangan'         => 'Portal untuk mengakomodasi aplikasi Buku Tamu/Sistem Informasi Penilaian Pengunjung (SIAP) dan Sistem Informasi RUP Terinput (SIPUT)',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 17,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0093',
                'nama_aset'          => 'Website Satpol PP Provinsi Bali [IKP]',
                'keterangan'         => 'Website Satpol PP Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 34,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0094',
                'nama_aset'          => 'Website Inspektorat Daerah Provinsi Bali',
                'keterangan'         => 'Website Inspektorat Daerah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 4,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0095',
                'nama_aset'          => 'Web-Site Sistem Informasi Keuangan Desa Adat',
                'keterangan'         => 'Sistem Informasi Keuangan Desa Adat',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 13,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0096',
                'nama_aset'          => 'Website RS Mata Bali Mandara [SIMRS]',
                'keterangan'         => 'Website',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 29,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0097',
                'nama_aset'          => 'Aplikasi Sistem Informasi Pengelolaan Sampah Berbasis Sumber Palemahan Kedas (SIPADAS)',
                'keterangan'         => '-',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 37,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0098',
                'nama_aset'          => 'Website DInas Kehutanan dan Lingkungan Hidup Provinsi Bali',
                'keterangan'         => '-',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 37,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0099',
                'nama_aset'          => 'Web-Site Jaringan Informasi Dokumentasi Hukum Adat',
                'keterangan'         => 'Jaringan Informasi Dokumentasi Hukum Adat',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 13,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0101',
                'nama_aset'          => 'MyHospital [SIMRS]',
                'keterangan'         => 'SIMRS RS Mata Bali Mandara. Aplikasi Lokal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 29,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0102',
                'nama_aset'          => 'E-Klaim [SIMRS]',
                'keterangan'         => 'Aplikasi Klaim BPJS Kesehaan. Aplikasi Lokal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 29,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0103',
                'nama_aset'          => 'Web BRIDA Provinsi Bali',
                'keterangan'         => 'Aplikasi mengenai layanan BRIDA Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 23,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0104',
                'nama_aset'          => 'Website Disdikpora',
                'keterangan'         => 'Website OPD untuk Disdikpora',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 28,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0105',
                'nama_aset'          => 'Website BPBD Provinsi Bali',
                'keterangan'         => 'Website BPBD Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 11,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0106',
                'nama_aset'          => 'Kelas Virtual',
                'keterangan'         => 'Aplikasi LMS untuk Satuan Pendidikan',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 28,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0107',
                'nama_aset'          => 'Sidokar [SIMRS]',
                'keterangan'         => 'Aplikasi dokumen akreditasi. Akses lokal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 29,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0110',
                'nama_aset'          => 'Website DPMPTSP Provinsi Bali',
                'keterangan'         => 'Website DPMPTSP Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 8,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0111',
                'nama_aset'          => 'EMR ( Electronic Medical Record ) [TI]',
                'keterangan'         => 'Sistem elektronik rekam medis. Akses Lokal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0112',
                'nama_aset'          => 'Vclaim BPJS [TI]',
                'keterangan'         => 'Aplikasi V - Claim BPJS',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0113',
                'nama_aset'          => 'E-Klaim [TI]',
                'keterangan'         => 'Aplikasi E-Klaim BPJS. Akses lokal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0115',
                'nama_aset'          => 'Satu Sehat [TI]',
                'keterangan'         => 'Aplikasi Pengiriman Data Satu Sehat. Akses Lokal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0116',
                'nama_aset'          => 'Dashboard Monitoring Satu Sehat [TI]',
                'keterangan'         => 'Aplikasi Dasboard Monitoring Satu Sehat. Akses lokal',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0117',
                'nama_aset'          => 'Website Resmi BKPSDM Provinsi Bali',
                'keterangan'         => 'Website Resmi BKPSDM Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 39,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0118',
                'nama_aset'          => 'SIMPEG',
                'keterangan'         => 'Aplikasi SIMPEG',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 39,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0119',
                'nama_aset'          => 'SIKEPO',
                'keterangan'         => 'Sistem Informasi Kinerja Pegawai Online',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 39,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0121',
                'nama_aset'          => 'SIMATA',
                'keterangan'         => 'Sistem Manajemen Talenta',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 39,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0122',
                'nama_aset'          => 'Bali Satu Data (Permintaan Informasi Publik) [IKP]',
                'keterangan'         => 'Layanan Permintaan Informasi Publik Pemerintah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0124',
                'nama_aset'          => 'Bali Data Sektoral (Bali Membangun) [Statistik]',
                'keterangan'         => 'Pengelolaan data statistik sektoral berbasis web',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0125',
                'nama_aset'          => 'Geoportal Provinsi Bali [Statistik]',
                'keterangan'         => 'Pengelolaan data geospasial daerah berbasis web',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0126',
                'nama_aset'          => 'SISTEM INFORMASI KOMPETENSI APARATUR',
                'keterangan'         => 'SISTEM INFORMASI KOMPETENSI APARATUR',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 39,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0127',
                'nama_aset'          => 'PERISAI [Persandian]',
                'keterangan'         => 'Sistem elektronik untuk melakukan PEngelolaan RISiko Aset Informasi di lingkup Pemerintah Provinsi Bali. PERISAI dikelola oleh Dinas Kominfos Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0128',
                'nama_aset'          => 'Website CSIRT [Persandian]',
                'keterangan'         => 'Website Baliprov-CSIRT',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0129',
                'nama_aset'          => 'Website Lentera Siber [Persandian]',
                'keterangan'         => 'Website Informasi Literasi Kesadaran Keamanan Siber Pemprov Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0130',
                'nama_aset'          => 'Newsletter [Persandian]',
                'keterangan'         => 'Aplikasi untuk berlangganan konten literasi keamanan siber Pemprov Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0131',
                'nama_aset'          => 'YANDIBALI [Persandian]',
                'keterangan'         => 'Aplikasi Layanan Persandian Pemprov Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0132',
                'nama_aset'          => 'WAZUH [Persandian]',
                'keterangan'         => 'Sistem elektronik untuk monitoring keamanan, deteksi ancaman, analisis log dan compliance',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0133',
                'nama_aset'          => 'eSign Client Service PDN [Persandian]',
                'keterangan'         => 'Aplikasi eSign untuk penerapan tanda tangan elektronik berbasis cloud',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0134',
                'nama_aset'          => 'eSign Client Service Pusdat [Persandian]',
                'keterangan'         => 'Aplikasi eSign untuk penerapan tanda tangan elektronik berbasis cloud',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0136',
                'nama_aset'          => 'Website Diskominfos Provinsi Bali [IKP]',
                'keterangan'         => 'Website yang menampilkan informasi terkait Dinas Komunikasi, Informatika dan Statistik Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0137',
                'nama_aset'          => 'Website PPID Provinsi Bali [IKP]',
                'keterangan'         => 'Media Penyebaran Informasi Publik Pemerintah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0138',
                'nama_aset'          => 'Bali Media Center [IKP]',
                'keterangan'         => 'Media Penyebaran Informasi Publik Pemerintah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 1,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0140',
                'nama_aset'          => 'Jadwal Praktek Web',
                'keterangan'         => 'Pengiputan Jadwal Praktek Dokter Spesialis',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0141',
                'nama_aset'          => 'DHIS 2 Kemenkes',
                'keterangan'         => 'Suatu sistem teknologi informasi komunikasi yang memproses dan mengintegrasikan seluruh alur proses pelayanan Rumah Sakit dalam bentuk jaringan koordinasi, pelaporan dan prosedur administrasi untuk memperoleh informasi secara tepat dan akurat, dan merupakan bagian dari Sistem Manajemen Informasi Kesehatan',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0142',
                'nama_aset'          => 'E-Tiket',
                'keterangan'         => 'Aplikasi di gunakan untuk merequest / pembaruan karena upadate system aplikasi',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0143',
                'nama_aset'          => 'Aplicares BPJS',
                'keterangan'         => 'plikasi ini merupakan bagian dari inovasi digital yang bertujuan untuk meningkatkan kualitas layanan serta mempermudah proses administrasi bagi peserta BPJS. Dengan Aplicares, peserta BPJS dapat melakukan berbagai aktivitas seperti pengecekan ketersediaan tempat tidur di rumah sakit hingga mendaftar antrian faskes BPJS secara online',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0144',
                'nama_aset'          => 'SSR Kemenkes',
                'keterangan'         => 'Media komunikasi dan informasi secara terintegrasi dari sistem rujukan berbasis kompetensi baik rujukan vertikal, horisontal maupun rujuk balik',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0145',
                'nama_aset'          => 'HFIS BPJS',
                'keterangan'         => 'Sistem informasi berbasis web untuk Fasilitas Kesehatan (Faskes) yang menjadi mitra BPJS Kesehatan untuk melakukan pelaporan dan monitoring data profil faskes',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0146',
                'nama_aset'          => 'Lupis BPJS',
                'keterangan'         => 'aplikasi yang memudahkan rumah sakit untuk menginput atau merekam data tagihan klaim yang tidak ditanggung oleh INA-CBG (Indonesian Case-Based Groups). Aplikasi ini membantu rumah sakit saat ada pasien yang menggunakan BPJS Kesehatan',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0147',
                'nama_aset'          => 'Snomed - CT Kemenkes',
                'keterangan'         => 'Meningkatkan mutu pelayanan kesehatan, memberikan kepastian hukum dalam penyelenggaraan dan pengelolaan rekam medis, menjamin keamanan, kerahasiaan, keutuhan, dan ketersediaan data rekam medis, serta mewujudkan penyelenggaraan dan pengelolaan rekam medis berbasis digital',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0148',
                'nama_aset'          => 'Ceraken Kebudayaan Bali [Server Diskominfos]',
                'keterangan'         => 'Bank Data Kebudayaan',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 21,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0149',
                'nama_aset'          => 'Aplikasi E-PBBKB',
                'keterangan'         => 'Aplikasi pembayaran pajak bahan bakar kendaraan bermotor',
                'sub_klasifikasi_id' => 'a1b8ffb3-40fb-48d5-8bec-aad7047294c7',
                'opd_id'             => 25,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0003',
                'nama_aset'          => 'SIWA',
                'keterangan'         => 'Sistem Sewa Aset Daerah Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b93053-d042-4c47-93a0-09463c537c03',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0015',
                'nama_aset'          => 'PACS RIS Mobile [SIMRS]',
                'keterangan'         => 'Aplikasi mobile viewer dari Radiology Information System - Picture Archiving and Communication System yang terintegrasi yang mengelola alur kerja radiologi dan gambar medis secara digital',
                'sub_klasifikasi_id' => 'a1b93053-d042-4c47-93a0-09463c537c03',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0066',
                'nama_aset'          => 'Aplikasi Antrean Pemprov Bali',
                'keterangan'         => 'Operasional dan Manajemen Data/konten Aplikasi Antrean Pemprov Bali',
                'sub_klasifikasi_id' => 'a1b93053-d042-4c47-93a0-09463c537c03',
                'opd_id'             => 5,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0069',
                'nama_aset'          => 'Made in Bali Mobile',
                'keterangan'         => 'Media katalog digital UMKM di Provinsi Bali berbasis aplikasi mobile',
                'sub_klasifikasi_id' => 'a1b93053-d042-4c47-93a0-09463c537c03',
                'opd_id'             => 24,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0092',
                'nama_aset'          => 'JDIH Mobile',
                'keterangan'         => 'Jaringan Dokumentasi dan Informasi Hukum Pemerintah Provinsi Bali berbasis mobile',
                'sub_klasifikasi_id' => 'a1b93053-d042-4c47-93a0-09463c537c03',
                'opd_id'             => 15,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0120',
                'nama_aset'          => 'APLIKASI ABSENSI',
                'keterangan'         => 'APLIKASI ABSENSI',
                'sub_klasifikasi_id' => 'a1b93053-d042-4c47-93a0-09463c537c03',
                'opd_id'             => 39,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0043',
                'nama_aset'          => 'SIMDA',
                'keterangan'         => 'Aplikasi SIMDA merupakan program aplikasi yang pada dasarnya digunakan untuk melakukan proses penatausahaan Barang Milik Daerah (BMD) secara otomatis dengan memanfaatkan pengolahan data elektronik',
                'sub_klasifikasi_id' => 'a1b93053-d143-4772-be2a-9870b32e4678',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'PL-0046',
                'nama_aset'          => 'LIS [SIMRS]',
                'keterangan'         => 'Laboratorium Information System (LIS). Aplikasi berbasis desktop untuk sistem informasi yang ada di laboratorium.',
                'sub_klasifikasi_id' => 'a1b93053-d143-4772-be2a-9870b32e4678',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
        ];

        foreach (array_chunk($data, 50) as $chunk) {
            DB::table('assets')->insertOrIgnore($chunk);
        }

        $this->command->info('✓ ' . count($data) . ' aset perangkat lunak berhasil di-seed.');
    }
}
