<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class AsetLayananSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0001',
                'nama_aset'          => 'APAR Kapasitas 4.5 kg',
                'keterangan'         => 'Alat Pemadam Kebakaran Portable 7 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0002',
                'nama_aset'          => 'APAR Kapasitas 6 kg',
                'keterangan'         => 'Alat Pemadam Kebakaran Portable 8 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0003',
                'nama_aset'          => 'Genset',
                'keterangan'         => 'Generator Set VGEN / VG200P 1 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0005',
                'nama_aset'          => 'UPS Sekretariat',
                'keterangan'         => '4 Unit UPS',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 23,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0006',
                'nama_aset'          => 'Fire Suppression System [SIMRS]',
                'keterangan'         => '1 unit / Sistem pemadam kebakaran otomatis yang dirancang untuk mendeteksi dan memadamkan api secara cepat sebelum menyebar luas pada ruang server',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0007',
                'nama_aset'          => 'ICA Online Sineware UPS Rackmount RN2100C [SIMRS]',
                'keterangan'         => '12 Unit UPS yang digunakan sebagi penyimpan daya pada panel jaringan',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0010',
                'nama_aset'          => 'Genset',
                'keterangan'         => 'Electric Generating set',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 10,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0011',
                'nama_aset'          => 'APAR',
                'keterangan'         => '32 unit Alat Pemadam kebakaran/Portable, 7 unit Alat Pemadam Kebakaran Lainnya',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 10,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0012',
                'nama_aset'          => 'UPS',
                'keterangan'         => 'Uninterruptible Power Supply (UPS)',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 10,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0021',
                'nama_aset'          => 'UPS APC SRT3000XLI 3KVA 230V [SIMRS]',
                'keterangan'         => '1 unit / UPS yang digunakan sebagai penyimpanan daya pada ruang server',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 27,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0022',
                'nama_aset'          => 'APAR Lantai 1',
                'keterangan'         => 'Alat Pemadam Api Ringan',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 11,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0023',
                'nama_aset'          => 'Genset',
                'keterangan'         => 'Genset untuk kegiatan darurat bencana',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 11,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0024',
                'nama_aset'          => 'APAR',
                'keterangan'         => 'Alat Pemadam Api Ringan',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 16,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0025',
                'nama_aset'          => 'Tabung Pemadam Kebakaran',
                'keterangan'         => 'Tabung Pemadam Kebakaran',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 3,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0026',
                'nama_aset'          => 'UPS',
                'keterangan'         => 'UPS untuk perangkat server dan router di Bappeda Bali',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 3,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0027',
                'nama_aset'          => 'APAR (ALAT PEMADAM API RINGAN)',
                'keterangan'         => 'Alat yang digunakan memadamkan api ringan dalam keadaan darurat',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 7,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0028',
                'nama_aset'          => 'Pengukur Suhu ruangan',
                'keterangan'         => 'Alat yang digunakan untuk mengetahui suhu ruangan pada ruangan arsip',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 7,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0029',
                'nama_aset'          => 'LCD Projector',
                'keterangan'         => 'LCD Projector/Infocus',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 16,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0030',
                'nama_aset'          => 'Televisi',
                'keterangan'         => '3 unit Televisi',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 16,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0031',
                'nama_aset'          => 'Kamera',
                'keterangan'         => '2 unit Kamera Mirrorless',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 16,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0032',
                'nama_aset'          => 'UPS APC',
                'keterangan'         => 'Untuk Router',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 30,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0033',
                'nama_aset'          => 'UPS Untuk Server SIPKD',
                'keterangan'         => '3 unit UPS 5000VA dan 1 unit 10000VA',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 14,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0035',
                'nama_aset'          => 'Genset (** tambahkan model dan tipe asset)',
                'keterangan'         => 'Genset',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 8,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0036',
                'nama_aset'          => 'UPS Prolink 1200va',
                'keterangan'         => 'Penyimpan Daya Listrik Sementara untuk peralatan jaringan',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 22,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0037',
                'nama_aset'          => 'Alat Pemadam Api Ringan (APAR)',
                'keterangan'         => '12 Unit Alat Pemadam Api Ringan (APAR)',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 6,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0040',
                'nama_aset'          => 'Alat Pemadam Kebakaran',
                'keterangan'         => '4 unit Alat Pemadam Kebakaran',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 4,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0041',
                'nama_aset'          => 'Alat Pemadam Kebakaran',
                'keterangan'         => '4 unit Alat Pemadam Kebakaran pada Lantai 2',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 4,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0043',
                'nama_aset'          => 'Kamera CCTV',
                'keterangan'         => '8 Unit Camera CCTV',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 2,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0044',
                'nama_aset'          => 'Apar',
                'keterangan'         => '4 Unit Alat Pemadam Api Ringan',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 2,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0045',
                'nama_aset'          => '1 Unit UPS',
                'keterangan'         => 'UPS sebagai stabilisasi tegangan listrik mikrotik RB1100',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 18,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0046',
                'nama_aset'          => 'Fire Alarm System',
                'keterangan'         => 'Alarm Kebakaran',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 18,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0047',
                'nama_aset'          => '2 Unit Alat Pembantu Kebakaran Gedung Sekretariat Dinas Perhubungan Provinsi Bali',
                'keterangan'         => '2 Unit Alat Pembantu Kebakaran Gedung Sekretariat Dinas Perhubungan Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 18,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0048',
                'nama_aset'          => '3 Unit Alat Pembantu Kebakaran Gedung II Dinas Perhubungan Provinsi Bali',
                'keterangan'         => '3 Unit Alat Pembantu Kebakaran Gedung II Dinas Perhubungan Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 18,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0049',
                'nama_aset'          => 'Smoke Detector',
                'keterangan'         => 'Smoke Detector di ruang Arsip Dinas Perhubungan Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 18,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0053',
                'nama_aset'          => 'Perangkat CCTV (1 Unit DVR dan 12 Unit Kamera CCTV) Dinas Perhubungan Provinsi Bali',
                'keterangan'         => 'Perangkat CCTV untuk memantau keadaaan (1 Unit DVR dan 12 Unit Kamera CCTV) di Dinas Perhubungan Provinsi Bali',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 18,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0054',
                'nama_aset'          => 'Unit Power Supply',
                'keterangan'         => '6 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 39,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0055',
                'nama_aset'          => 'APAR Alat Pemadam/Portable',
                'keterangan'         => '5 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 39,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0056',
                'nama_aset'          => 'Alat Pemadam Api Ringan (APAR)',
                'keterangan'         => '4 Unit alat portabel untuk memadamkan kebakaran kecil di tahap awal',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 15,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0059',
                'nama_aset'          => 'CCTV',
                'keterangan'         => 'Memantau dan mengawasi area kantor',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 24,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0060',
                'nama_aset'          => 'Genset',
                'keterangan'         => 'Mesin pembangkit listrik untuk Gedung Paripurna DPRD',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 33,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0061',
                'nama_aset'          => 'UPS',
                'keterangan'         => 'Sebagai backup dan pengaman power kepada perangkat PC dan Laptop',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 24,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0062',
                'nama_aset'          => 'UPS Sekretariat',
                'keterangan'         => '3 Unit UPS',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 23,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0063',
                'nama_aset'          => 'UPS Sekretariat',
                'keterangan'         => '3',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 23,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0064',
                'nama_aset'          => 'APAR Lantai 2',
                'keterangan'         => 'Alat Pemadam Api Ringan',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 11,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0065',
                'nama_aset'          => 'APAR Lantai 3',
                'keterangan'         => 'Alat Pemadam Api Ringan',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 11,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0067',
                'nama_aset'          => 'Rak server',
                'keterangan'         => '4 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d070-436b-9cd1-8a5504bf8133',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0004',
                'nama_aset'          => 'Genzet Perkins Tipe 2200 Series [TI]',
                'keterangan'         => '1 Unit  Genzet untuk sumber daya cadangan saat listrik di Ruang Server',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 26,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0013',
                'nama_aset'          => 'UPS ICA SE 1100 -1000VA [Datin]',
                'keterangan'         => '3 UPS untuk menyediakan daya cadangan sementara saat listrik padam dan menstabilkan tegangan listrik pada Server',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 26,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0014',
                'nama_aset'          => 'UPS Pendukung PC Acer Altos / City 2000 (TU)',
                'keterangan'         => '2 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 32,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0016',
                'nama_aset'          => 'APAR Apron / 9 Kg Ruang VIP Pimpinan (TU)',
                'keterangan'         => '1 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 32,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0017',
                'nama_aset'          => 'APAR Apron / 9 Kg Lobby Kantor (TU)',
                'keterangan'         => '1 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 32,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0018',
                'nama_aset'          => 'APAR Apron / 9 Kg Tangga Lantai 2 Kantor (TU)',
                'keterangan'         => '1 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 32,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0038',
                'nama_aset'          => 'Printer (** tambahkan model dan tipe asset) [Kantor DKLH] (**Printer termasuk ke dalam perangkat keras)',
                'keterangan'         => '18 Unit (**sesuaikan dengan model dan tipe aset)',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 37,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0039',
                'nama_aset'          => 'Alat Pemadam Api Ringan [Kantor DKLH]',
                'keterangan'         => '1 Unit',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 37,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0042',
                'nama_aset'          => 'UPS Server {**penginputan UPS Server besar dan kecil agar dipisah}',
                'keterangan'         => 'APC Smart UPS Server Kecil 3, UPS Server Besar 1',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0050',
                'nama_aset'          => 'Generator Set [TI]',
                'keterangan'         => '1 unit',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0051',
                'nama_aset'          => 'Sensor Suhu [TI]',
                'keterangan'         => '3 unit',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0052',
                'nama_aset'          => 'APAR [TI]',
                'keterangan'         => '25 unit / Massafe Fire Extinguisher Alat Pemadam Kebakaran',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 36,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'kode_aset'          => 'SP-0066',
                'nama_aset'          => 'Handy Talki (HT) [Bidang 2]',
                'keterangan'         => 'Alat Komunikasi',
                'sub_klasifikasi_id' => 'a1b93053-d0a0-4b33-9a1d-309d9d49d718',
                'opd_id'             => 34,
                'tahunaktif_id'      => 'a1b8ffb3-3b4d-43c6-9dfe-a2895308aa80',
                'created_by'         => 1,
                'updated_by'         => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ],
        ];

        foreach (array_chunk($data, 50) as $chunk) {
            DB::table('assets')->insertOrIgnore($chunk);
        }

        $this->command->info('✓ ' . count($data) . ' aset layanan berhasil di-seed.');
    }
}